name: basemind
description: The dart client for the BaseMind.AI platform
version: 1.0.1
homepage: https://github.com/basemind-ai/sdk-dart
repository: https://github.com/basemind-ai/sdk-dart
topics:
    - basemind
    - ai
    - grpc

environment:
    sdk: '>=2.19.0 <4.0.0'

dependencies:
    async: ^2.11.0
    collection: ^1.18.0
    grpc: ^3.2.4
    logging: ^1.2.0
    protobuf: ^3.1.0

dev_dependencies:
    build_runner: ^2.4.7
    lints: ^3.0.0
    mockito: ^5.4.4
    test: ^1.24.0
