name: basemind
description: 'BaseMind.AI SDK for Flutter: Streamlines AI model integration in Flutter apps. Features serverless AI, fast response with GO-based gRPC server, and a vendor-neutral approach. Includes a UI for creating and managing prompt and model configurations. Optimized for efficient and flexible AI-powered mobile experiences.'
version: 1.0.1
homepage: https://github.com/basemind-ai/sdk-dart
repository: https://github.com/basemind-ai/sdk-dart
topics:
    - basemind
    - ai
    - grpc
    - gpt4
    - openai

environment:
    sdk: '>=2.19.0 <4.0.0'

dependencies:
    async: ^2.11.0
    collection: ^1.18.0
    grpc: ^3.2.4
    logging: ^1.2.0
    protobuf: ^3.1.0

dev_dependencies:
    build_runner: ^2.4.7
    lints: ^3.0.0
    mockito: ^5.4.4
    test: ^1.24.0
