version: '3'

tasks:
    setup:
        desc: Setup the Project
        cmds:
            - brew update && brew upgrade
            - command -v flutter &> /dev/null && flutter upgrade
            - command -v dart &> /dev/null || brew install dart
            - command -v protoc &> /dev/null || brew install protobuf
            - command -v pre-commit &> /dev/null || brew install pre-commit
            - pre-commit install && pre-commit install --hook-type commit-msg && pre-commit install-hooks
    update:
        desc: Update Components and Dependencies
        cmds:
            - brew update && brew upgrade
            - command -v flutter &> /dev/null && flutter upgrade
            - flutter pub upgrade
            - pre-commit autoupdate
    lint:
        desc: Lint the project
        cmds:
            - dart format write
            - dart fix --apply
            - pre-commit run --show-diff-on-failure --color=always --all-files
            - dart analyze
    generate:
        desc: Generate swift stubs from the proto file
        cmds:
            - dart pub global activate protoc_plugin
            - export PATH="$PATH:$HOME/.pub-cache/bin"
            - rm -rf tmp || true
            - mkdir -p tmp
            - protoc --dart_out=grpc:tmp proto/gateway/v1/gateway.proto
            - rm -rf lib/src || true
            - mv tmp/proto/gateway/v1 lib/src
            - rm -rf tmp
    coverage:
        desc: Generate a coverage report
        cmds:
            - dart pub global activate coverage
            - dart pub global run coverage:test_with_coverage
