name: 'Publish'
on:
    release:
        types:
            - published

jobs:
    publish:
        permissions:
            id-token: write
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
