name: 'Publish'
on:
    release:
        types:
            - published

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Publish
              uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
