name: 'Test'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
#env:
#    DEEPSOURCE_DSN: ${{secrets.DEEPSOURCE_DSN}}
jobs:
    test:
        runs-on: macos-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Setup Dart
              uses: dart-lang/setup-dart@v1
            - name: Enable Coverage
              run: dart pub global activate coverage
            #            - name: Download the DeepSource CLI
            #              run: curl https://deepsource.io/cli | sh
            - name: Run tests with Coverage
              run: dart pub global run coverage:test_with_coverage
#            - name: Upload Coverage Report
#              run: ./bin/deepsource report --analyzer test-coverage --key dart --value-file ./coverage/lcov.info
