name: 'Test'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Dart
              uses: dart-lang/setup-dart@v1
            - name: Load Cached Dart Dependencies
              id: cached-dart-dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.dart_tool/
                  key: dart-3${{ hashFiles('pubspec.lock') }}
            - name: Install Dependencies
              run: dart pub get
            - name: Run tests
              run: dart test
