name: 'Validate'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
            - name: Load Cached Dart Dependencies
              id: cached-dart-dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.dart_tool/
                  key: dart-3${{ hashFiles('pubspec.lock') }}
            - name: Install Dependencies
              run: flutter pub get
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
            - name: Install Task
              uses: arduino/setup-task@v1
            - name: Install Pre-Commit
              run: python -m pip install pre-commit && pre-commit install
            - name: Load Cached Pre-Commit Dependencies
              id: cached-pre-commit-dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit/
                  key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
            - name: Lint
              run: task lint
